name: Build and Push Dev Docker Image

on:
  push:
    branches:
      - dev  # Only trigger on dev branch

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Build and push dev Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/chrishansentech/plexsubsync:dev
            ghcr.io/chrishansentech/plexsubsync:dev-${{ env.SHORT_SHA }}
